package webTest;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class AmazonCarrinhoSIDE {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        System.setProperty("webdriver.chrome.driver", "drivers/chrome/chromedriver.exe");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void amazonCarrinho() {
        driver.get("https://www.amazon.com.br/");
        driver.manage().window().setSize(new Dimension(1366, 728));
        driver.findElement(By.cssSelector("#CardInstancemRU-utUZ4MDMGP3JWIgWjw .a-spacing-none:nth-child(1) img")).click();
        driver.findElement(By.id("add-to-cart-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".a-link-normal > .celwidget"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
    }
}

